apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: samplepubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: daprauthredis:6379
  - name: redisPassword
    value: ""
    